# sonar-project.properties

# Project Identification
sonar.projectKey=ProCircleTeam_pro-mobile
sonar.organization=procircleteam
sonar.projectName=pro-mobile
sonar.projectVersion=1.0

# Paths
sonar.sources=lib
sonar.exclusions=android/**,ios/**,macos/**,windows/**,linux/**,test/**,.dart_tool/**,build/**

# Coverage
sonar.dart.coverage.reportPaths=coverage/lcov.info

# Host
sonar.host.url=https://sonarcloud.io
sonar.token=9a172b62d89001bd0748104e111f57eb360a2f6c

# Language (force Dart)
sonar.language=dart
